# Site settings
title: Iced Tea Labs
subtitle: Share to be shared
email: trinhlbk1991@gmail.com
description: "Check out our Google Play Store"
baseurl: "" # the subpath of your site, e.g. /blog
url: http://icedtealabs.com # the base hostname & protocol for your site
author: Trinh Le

paginate: 11
paginate_path: /page:num/

#Jekyll
permalink:          /:categories/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Social settings
facebook_url: https://www.facebook.com/IcedTeaLabs
github_url: https://github.com/trinhlbk1991
instagram_url: https://www.instagram.com/trinhlbk/
linkedin_url: https://www.linkedin.com/in/trinhlbk1991
twitter_url: https://twitter.com/trinhlbk1991

disqus_shortname:   icetea09

sass:
  style: compressed

plugins: [jekyll-paginate]
