# Site
title:              Ice Tea 09
bio:                'Share to be shared'
description:        ""
reading_time:       true
words_per_minute:   150
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
#url:                http://localhost:4000
url:                http://icetea09.com

# Jekyll
permalink:          /:categories/:year/:month/:day/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   icetea09

# Social
# if you don't have any of social below, comment the line.
#google:
#  plus:             TrinhLetrinhlbk
  #analytics:        UA-48722139-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            khanhtrinhspk
#facebook:           lebakhanhtrinh
github:             trinhlbk1991
stackoverflow:      2134265/trinh-le
linkedin:           trinhlbk1991
#xing:              username
instagram:          trinhlbk
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            UCNrNsDFoxbeOYi6Ap5SsZpQ
#soundcloud:        username
#weibo:             username
flickr:             trinhlbk1991
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
